version: "3.8"
services:
  ecr-proxy:
    image: proreact/aws-ecr-proxy:1.21.3
    ports:
      - target: 443
        published: 5000
        protocol: tcp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    environment:
      RESOLVER: 169.254.169.253
