version: "3.8"
services:
  ecr-proxy:
    image: aws-ecr-proxy:1.25
    ports:
      - target: 80
        published: 5770
        # host_ip: 127.0.0.1
        protocol: tcp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      placement:
        constraints:
          - "node.role==manager"
    environment:
      RESOLVER: 169.254.169.253
    secrets:
      - source: ecr-registry-htpasswd
        target: /etc/nginx/registry_htpasswd
      - source: ecr-aws-config-ro
        target: /root/.aws/config
    # labels:
    #   erova.swarm.runmode: "one-time"

secrets:
  ecr-registry-htpasswd:
    external: true
  ecr-aws-config-ro:
    external: true
