version: "3.8"
services:
  ecr-proxy:
    build:
      context: .
    logging:
      driver: json-file
    image: aws-ecr-proxy:1.25
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    environment:
      # AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      # AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      REGION: eu-west-1
      #RESOLVER: 169.254.169.253
      RENEW_TOKEN: 30s
    volumes:
    - "./configs/nginx/nginx-docker-registry-v2.conf:/etc/nginx/nginx-docker-registry-v2.conf"